# Generated by Django 5.0.3 on 2024-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('Datepub', models.DateField(blank=True)),
                ('prix', models.FloatField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
