# Generated by Django 5.0.3 on 2024-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('plublication', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
